version: "3.8"

services:
  localstack:
    container_name: "moggies-localstack_main"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      - SERVICES=s3,dynamodb,apigateway,cloudwatch,kms,events
      - DEFAULT_REGION=eu-west-1
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
#   localstack-s3-ui:
#     container_name: localstack-s3-ui
#     depends_on: [localstack]
#     image: gosuper/localstack-s3-ui
#     ports:
#       - 9000:9000
#     environment:
#       - API_REQ_FILE_PATH=/tmp/localstack/data/recorded_api_calls.json // Required
#       - PORT=9000
#     volumes:
#       - "${TMPDIR}/localstack:/tmp/localstack"
